<section class="relative py-5 overflow-hidden bg-ngemi-dark-light border-y border-ngemi-orange/10">
    <div class="marquee-track flex animate-marquee whitespace-nowrap">
        <span class="mx-8 text-ngemi-orange text-sm font-bold tracking-[0.2em] uppercase">September 5, 2026</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream text-sm font-bold tracking-[0.2em] uppercase">Berlin, Germany</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange/60 text-sm font-bold tracking-[0.2em] uppercase">Doors Open 14:00</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/60 text-sm font-bold tracking-[0.2em] uppercase">Live Performances</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange text-sm font-bold tracking-[0.2em] uppercase">Kenyan Cuisine</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream text-sm font-bold tracking-[0.2em] uppercase">Cultural Exhibitions</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange/60 text-sm font-bold tracking-[0.2em] uppercase">Family Friendly</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/60 text-sm font-bold tracking-[0.2em] uppercase">Vendor Market</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange text-sm font-bold tracking-[0.2em] uppercase">Where Culture Lives</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream text-sm font-bold tracking-[0.2em] uppercase">September 5, 2026</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange/60 text-sm font-bold tracking-[0.2em] uppercase">Berlin, Germany</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/60 text-sm font-bold tracking-[0.2em] uppercase">Live DJs</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange text-sm font-bold tracking-[0.2em] uppercase">Doors Open 14:00</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
    </div>
</section>
