<section class="relative py-5 overflow-hidden bg-ngemi-dark-light border-y border-ngemi-orange/10">
    <div class="marquee-track flex animate-marquee whitespace-nowrap">
        <span class="mx-8 text-ngemi-orange/60 text-sm font-bold tracking-[0.2em] uppercase">2nd Edition</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Nairobi</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">London</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Seattle</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Tacoma</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Paris</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange text-sm font-bold tracking-[0.2em] uppercase">Now Berlin</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange/60 text-sm font-bold tracking-[0.2em] uppercase">15,000+ Attendees</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange/60 text-sm font-bold tracking-[0.2em] uppercase">2nd Edition</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Nairobi</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">London</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Seattle</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Tacoma</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-cream/30 text-sm font-bold tracking-[0.2em] uppercase">Paris</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange text-sm font-bold tracking-[0.2em] uppercase">Now Berlin</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
        <span class="mx-8 text-ngemi-orange/60 text-sm font-bold tracking-[0.2em] uppercase">15,000+ Attendees</span>
        <span class="mx-4 text-ngemi-orange/20">&#10022;</span>
    </div>
</section>
